/*TESTANDO SE A TABELA ACEITA CAMPOS COM VALORES NULLO*/
INSERT INTO compras (valor, data, recebida, observacoes)
VALUES (150, '2016-01-04', 1, NULL);

/*SELECIONANDO TODOS OS VALORES QUE TEM OBSERVAÇÕES VAZIO*/
SELECT * FROM compras WHERE observacoes IS NULL;

/*DELETANDO TODOS OS VALORES QUE TEM OBSERVAÇÕES VAZIO*/
DELETE FROM compras WHERE observacoes IS NULL;

/*ALTERANDO AS COLUNAS DE UMA TABELA*/
ALTER TABLE compras MODIFY COLUMN observacoes VARCHAR(255) NOT NULL;

/*DEFININDO VALORES COMO PADRAO*/
ALTER TABLE compras MODIFY COLUMN recebida tinyint(1) DEFAULT 0;

/*DEFININDO O TEMPO ATUAL COMO DEFAULT PARA DATA*/
ALTER TABLE compras MODIFY COLUMN data DATETIME DEFAULT now();

/*DEFININDO O TEMPO ATUAL COMO DEFAULT PARA DATA (COM CURRENT_TIMESTAMP)*/
ALTER TABLE compras MODIFY COLUMN data DATETIME DEFAULT CURRENT_TIMESTAMP;